<?php require_once('./include/config.php'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>::::: Terms &amp; Conditions | Xtra Lash:::::</title>
<link href="juicy-5-style.css"rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.text {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10pt;
	font-weight: normal;
}
.footer-text {font-family: arial; font-size: 9pt; font-weight: normal; margin: 0px; padding:0px; line-height:18px;}
.footer-textb {font-family: arial; font-size: 10pt; font-weight: bold; margin: 0px; padding:0px; line-height:18px;}
-->
</style>
</head>

<body>
<?php require_once('tracking/google-analytics.php'); ?>
<!--<table width="536" border="0" align="left" cellpadding="0" cellspacing="0" style="text-align:justify; padding:10px;">
 
  <tr>
    <td width="536" class="text"><h2 align="center"><u>Terms &amp; Conditions</u></h2>
The  following terms and conditions are a legally binding agreement which govern  your use of our website and purchase of products on our website.  Please review the entire agreement carefully.  When you submit an order for our product you  are certifying that you have read and agree to all terms and conditions  contained in this agreement. 
      <h2 align="center"><u>Trial Offer and Continuity Plan  Summary</u></h2>
      <p><strong>Free Trial Offer: </strong></p>
    <p>To help you get started, we offer a 14-days trial of <?php print PRODUCT_NAME; ?> with enrollment in our home delivery program. You can try <?php print PRODUCT_NAME_SHORT; ?> risk free to determine for yourself if this product is right for you. When you submit your order, you agree to pay the non-refundable shipping &amp; handling charge of <strong>$<?php print SHIP_AMT; ?></strong> for your trial sample. If you find that the product is not right for you, simply call our Customer Service Center at <?php print SITE_PH_NO; ?> or send an email to customerservice@envisage-skin.com to cancel before the end of your 14-day trial period and you will not be charged anything else. Your 14-day trial period begins once the product is delivered. If you do not receive your free trial bottle within five (5) days of ordering, please contact our Customer Service Center or by email at customerservice@envisage-skin.com. Upon cancellation, you do need to return the unused portion.</p>
      <p>If you do not cancel before the end of your 14-day trial period, we will ship you a 30-day supply of <?php print PRODUCT_NAME_SHORT; ?> every thirty (30) days thereafter until you choose to cancel these continuing shipments. No further notice will be sent to you. Upon shipment each thirty (30) days, we will automatically charge the credit card you used to order your free trial bottle the price of <strong><?php print TOTAL_AMOUNT; ?></strong> per bottle.&nbsp; </p>
      <p><strong>Cancellations: </strong></p>
      <p>You may cancel your continuing shipments at any time if you are not completely satisfied with the product by notifying Company at <?php print SITE_PH_NO; ?>. However, unless you are canceling pursuant to the 14 Day Trial Period set forth hereinabove, we will not refund any amounts previously paid up to the date of cancellation or termination. You shall not receive any pro-rata refund for partial months and you remain liable for any and all unpaid charges billed through the date of cancellation. You understand and agree that cancellation of the continuity program is your sole right and remedy with respect to any dispute with Company. </p>
      <p><strong>100% Refund Policy: </strong></p>
      <p>If you are not happy with your purchase please call our customer service number and one of our representatives will be happy to help you process a refund only if the product has not been opened. You will also be advised on the best way of returning our product. Packages marked Return to Sender, Refused, Attempted not known will not be processed or refunded. By hitting the Submit Button (order button) on our site shows you are aware of and agree to our return policy. &nbsp;&nbsp;<!-- Due to the nature of our products and to protect our customers we will not accept return products.&nbsp; We will not attempt to resell or restock any of these items. </p>
      <p><strong>Negative Option Clause - I understand that this consumer transaction involves a negative option, and that I may be liable for payment of future goods and services under the terms of this agreement if I fail to notify the supplier not to supply the goods or services described. You may cancel at any time by calling <?php print SITE_PH_NO; ?>. </strong></p>
      <p>&nbsp; </p>
      <h2>GENERAL TERMS AND CONDITIONS </h2>
      <p>Thank you for visiting a Sheridan Labs Ltd(“Company”) website (“Website”). This Website is intellectual property of Sheridan Labs Ltd (&quot;Company,” &quot;we,&quot; or &quot;us&quot;). By accessing this Website, purchasing products or services from this Website you agree to the following Website Terms and Conditions (“ Terms and Conditions ”). The posted Privacy Policy (“ Privacy Policy ”) and any and all other posted operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time, are expressly incorporated herein by reference (collectively, the “Agreement”). <strong>Please review the Agreement carefully. If you do not agree to the terms and conditions contained within the Agreement in its entirety, you are not authorized to use the Website or purchase products from the website in any manner or form whatsoever. </strong></p>
      <p><strong>INTERNET TECHNOLOGY AND THE APPLICABLE LAWS, RULES, AND REGULATIONS CHANGE FREQUENTLY. ACCORDINGLY, WE RESERVE THE RIGHT TO MAKE CHANGES TO THIS TO WEBSITE AT ANY TIME. YOUR CONTINUED USE OF THE WEB SITE CONSTITUTES YOUR AGREEMENT TO ANY NEW OR MODIFIED PROVISION OF THIS AGREEMENT THAT MAY BE POSTED ON THE WEB SITE. </strong></p>
      <p>SHERIDAN LABS LTD IS NOT A COVERED ENTITY FOR PURPOSES OF THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT OF 1996 (“HIPAA”), NOR IS THE INFORMATION PROVIDED BY YOU TO COMPANY CONSIDERED PROTECTED HEALTH INFORMATION UNDER HIPAA. AS SUCH, THE ADDITIONAL PRIVACY AND SECURITY PROTECTIONS AFFORDED TO CONSUMERS/PATIENTS UNDER HIPAA ARE NOT CONTEMPLATED BY, NOR CONTAINED WITHIN, THE AGREEMENT. </p>
      <p><strong>1. Acceptance of Agreement. </strong> You agree to the terms and conditions outlined in the Agreement with respect to your use of the Website including, but not limited to, your purchase of Online Products through this Website. This Agreement constitutes the entire and only agreement between you and Company with respect to your use of the Website and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to your use of the Website, the content contained therein and/or the analyses, research, opinions and other information provided by or through the Website. Company may change the Agreement, in whole or in part, at any time without specific notice to you. The latest Agreement will be posted on the Website. Your continued use of the Website following posted notice constitutes your acceptance of all of the terms and conditions contained within the Agreement in effect at that time. Therefore, you should regularly check this page for updates and/or changes. Unless explicitly stated otherwise, any future offer(s) or product(s) made available to you on the Website that augment(s) or otherwise enhance(s) the current features of the Website shall be subject to the Agreement posted at the time of your purchase. Company is not responsible or liable in any manner whatsoever for your inability to use the Website and/or obtain any Online Products. The Website and Products offered are available only to individuals who are at least eighteen (18) years of age and can enter into legally binding contracts. Company reserves the right, in its sole discretion, to deny any order of anyone at any time and for any reason, whatsoever. You certify that you are eighteen (18) years of age and agree to provide true, accurate, current and complete information when prompted for such information. </p>
      <p><strong>2. Orders/Billing. </strong>In consideration for the Products you order from Company, you agree to pay the sums listed below at the time such sums are due and owing. You shall have the choice to pay with a credit card or debit card. Company's authorization to provide and bill you is obtained by way of your electronic signature. Once an electronic signature is submitted, this electronic order constitutes an electronic letter of agency. Company's reliance upon your electronic signature is specifically sanctioned by the Uniform Electronic Transactions Act and the Electronic Signatures in Global and National Transactions Act. Both laws specifically preempt all state laws that recognize only paper and handwritten signatures. </p>
      <p><strong>Contact Us.</strong> If you have any questions about the Agreement, Product or about the practices of Company, please feel free to call us at <?php print SITE_PH_NO; ?> Mon - Fri from 9am – 6pm MST. </p></td>
  </tr>
</table>
-->
<table width="536" border="0" align="left" cellpadding="0" cellspacing="0" style="text-align:justify; padding:10px;">
 
  <tr>
    <td width="536" class="text"><h2 align="center"><u>Terms &amp; Conditions</u></h2>
      <p>The following terms and conditions are a legally binding  agreement which govern your use of our website and purchase of products on our  website.  Please review the entire  agreement carefully.  When you submit an  order for our product, you are certifying that you have read and agree to all  terms and conditions contained in this agreement.</p>
      <h2 align="center"><u>Trial Offer and Continuity Plan  Summary</u></h2>
      <p><strong><span class="footer-textb">US Customer Support:</span> <?php print US_SITE_PH_NO; ?></strong><br />
      </p>
      <p> <span class="footer-textb"><a href="mailto:<?php print SITE_EMAIL; ?>" class="footer-textb"><?php print SITE_EMAIL; ?></a></span>&nbsp;</p>
      <p>To help you get started, we offer a 14-days trial of <span class="footer-text"><?php print PRODUCT_NAME; ?></span> with the  eligibility of automatic enrollment in our home delivery program. You can try <span class="footer-text"><?php print PRODUCT_NAME; ?></span> risk free to  determine for yourself, if this product is right for you. When you submit your  order, you automatically agree to pay the non-refundable discounted shipping  &amp; handling cost of $<span class="footer-text"><?php print SHIP_AMT; ?></span> for your trial for a full 30 day supply of <span class="footer-text"><?php print PRODUCT_NAME; ?></span>. <br />
        <br />
        If you  find that the product is not right for you, simply call our Customer Support  Center   or the numbers shown on your bank statement you can also send an email to cancel your membership before the end of your 14-day trial period and you  will not be charged the full price of the <span class="footer-text"><?php print PRODUCT_NAME; ?></span>. Your  14-day trial period begins at the date of  order our products are normally delivered within 3 to 5 business days from the  time of ordering. If you do not receive your trial bottles within five (5) business  days of placing the order, please contact our Customer Service Center or numbers  shown on your bank statement our support staff is available to give you more  updated information on the estimated delivery time along with the tracking info.  <br />
  <br />
        If you do not cancel before the end of your 14-day trial, we  conceder you as our valued member of home delivery program and charge the  credit card on file the full price of ninety-nine dollars. <span class="footer-text"><?php print TOTAL_AMOUNT_US; ?></span> will be charged on the 30th day from the order and  30days   there after your credit card on file will be billed for the fresh pair  of full 30-day supply of <span class="footer-text"><?php print PRODUCT_NAME; ?></span> until you choose to cancel the home delivery program. No further notice will be  sent by the Company. </p>
      <p><strong>Address:</strong></p>
      <p><?php print US_COMPANY_NAME; ?><br />
        <?php print US_COMPANY_ADDRESS; ?><br />
        <span class="footer-text"><?php print US_SITE_PH_NO; ?></span></p>
      <p>&nbsp;</p>
      <p><span class="footer-textb"> UK  Customer Support: <?php print UK_SITE_PH_NO; ?></span> <span class="footer-textb">| <a href="mailto:<?php print SITE_EMAIL; ?>" class="footer-textb"><?php print SITE_EMAIL; ?></a></span></p>
      <p>To help you get started, we offer a 14-days trial of <span class="footer-text"><?php print PRODUCT_NAME; ?></span> with the  eligibility of automatic enrollment in our home delivery program. You can try <span class="footer-text"><?php print PRODUCT_NAME; ?></span> risk free to  determine for yourself, if this product is right for you. When you submit your  order, you automatically agree to pay the non-refundable discounted shipping  &amp; handling cost of <span class="footer-text">£</span><span class="footer-text"><?php print SHIP_AMT; ?></span> for your trial for a full 30 day supply of <span class="footer-text"><?php print PRODUCT_NAME; ?></span>. <br />
        <br />
        If you  find that the product is not right for you, simply call our Customer Support  Center   or the numbers shown on your bank statement you can also send an email to cancel your membership before the end of your 14-day trial period and you  will not be charged the full price of the <span class="footer-text"><?php print PRODUCT_NAME; ?></span>. Your  14-day trial period begins at the date of  order our products are normally delivered within 3 to 5 business days from the  time of ordering. If you do not receive your trial bottles within five (5) business  days of placing the order, please contact our Customer Service Center or numbers shown on your bank statement our support staff is available to give you more  updated information on the estimated delivery time along with the tracking info.  <br />
  <br />
        If you do not cancel before the end of your 14-day trial, we  conceder you as our valued member of home delivery program and charge the  credit card on file the full price of ninety-five pounds. <span class="footer-text"><?php print TOTAL_AMOUNT_UK; ?></span> will be charged on the 30th day from the order and  30days   there after your credit card on file will be billed for the fresh pair  of full 30-day supply of <span class="footer-text"><?php print PRODUCT_NAME; ?></span> until you choose to cancel the home delivery program. No further notice will be  sent by the Company. </p>
      <p><span class="footer-textb">Address:<br />
        <br />
        <span class="footer-text"><?php print UK_COMPANY_NAME; ?><br />
          <?php print UK_COMPANY_ADDRESS; ?><br />
          <?php print UK_SITE_PH_NO; ?></span><br />
      </span></p>
      <p><br />
      </p>
      <p><strong>Cancellations: </strong></p>
      <p>You may cancel your continuity shipments within, the given  stipulated period, any time. If you are not completely satisfied with the  product, by calling  (US) <span class="footer-text"><?php print US_SITE_PH_NO; ?> or (UK) <?php print UK_SITE_PH_NO; ?></span> or numbers shown on your bank statement,  However, unless  you are cancelling pursuant to the 14 Day Trial set forth herein and stated as above,  the company will not refund any amounts previously paid up to the date of  cancellation. For termination, you shall not receive any pro-rate refund for  the partial month&rsquo;s payments and you will be deemed, to remain liable for any  and all unpaid charges, billed through to the date of cancellation. We consider  that you understand and agree that cancellation of the continuity program is  your sole right and remedy with respect to any dispute with the Company. The  Company henceforth considers that, you have read, agreed and (met) all the  required terms and conditions of the company Policy.</p>
      <p><br />
        <strong>Customer Support: </strong><a href="mailto:<?php print SITE_EMAIL; ?>" class="footer-textb"><?php print SITE_EMAIL; ?></a><br />
      </p>
      <p><strong>Refund Policy: </strong></p>
      <p>If you are not happy with your purchase, please call our  customer service number (US) <span class="footer-text"><?php print US_SITE_PH_NO; ?> or (UK) <?php print UK_SITE_PH_NO; ?></span> or numbers shown on your bank statement and one of our representatives will be happy to  help you process a refund.  All products (unused  portion) coming back are subject to restocking fee and refund amount could vary  by the condition of the bottles. You will also be advised on the best way of  returning our product, product in possession for 30 days or more will not be  considered refundable.</p>
      <p><br />
        We strongly engorge our valued home delivery program members  to call our customer support staff to obtain RMA ( Return Merchandize  Authorization) Number to help us expedite the   refund process  Packages marked  Return to Sender or refuse delivery may take longer than normal time to credit  processing time. The refund will require 3 to 5 business days for approval. By  hitting the Submit Button (order button) on our site shows that you are fully aware  of and agree to all our terms of our stated refund and return policy.   </p>
      <p>
        <!-- Due to the nature of our products and to protect our customers we will not accept return products.&nbsp; We will not attempt to resell or restock any of these items.-->
        <strong>Negative Option Clause - I understand that this consumer transaction involves a negative option, and that I may be liable for payment of future goods and services under the terms of this agreement if I fail to notify the supplier not to supply the goods or services described. You may cancel at any time by calling <span class="footer-textb"><?php print UK_SITE_PH_NO; ?></span>. </strong></p>
      <p><strong>Return Address:<br />
        <br />
        US :</strong><strong> <?php print US_COMPANY_NAME; ?> <?php print RETURN_ADDRESS_US; ?></strong><strong><br />
  <br />
          UK :</strong><strong> <?php print UK_COMPANY_NAME; ?> <?php print UK_COMPANY_ADDRESS; ?></strong></p>
      <h2>GENERAL TERMS AND CONDITIONS </h2>
      <p>Thank you for visiting a Sheridan Labs Inc(“Company”) website (“Website”). This Website is intellectual property of Sheridan Labs Inc (&quot;Company,” &quot;we,&quot; or &quot;us&quot;). By accessing this Website, purchasing products or services from this Website you agree to the following Website Terms and Conditions (“ Terms and Conditions ”). The posted Privacy Policy (“ Privacy Policy ”) and any and all other posted operating rules, policies, price schedules and other supplemental terms and conditions or documents that may be published from time to time, are expressly incorporated herein by reference (collectively, the “Agreement”). <strong>Please review the Agreement carefully. If you do not agree to the terms and conditions contained within the Agreement in its entirety, you are not authorized to use the Website or purchase products from the website in any manner or form whatsoever. </strong></p>
      <p><strong>INTERNET TECHNOLOGY AND THE APPLICABLE LAWS, RULES, AND REGULATIONS CHANGE FREQUENTLY. ACCORDINGLY, WE RESERVE THE RIGHT TO MAKE CHANGES TO THIS TO WEBSITE AT ANY TIME. YOUR CONTINUED USE OF THE WEB SITE CONSTITUTES YOUR AGREEMENT TO ANY NEW OR MODIFIED PROVISION OF THIS AGREEMENT THAT MAY BE POSTED ON THE WEB SITE. </strong></p>
      <p>Sheridan Labs Inc IS NOT A COVERED ENTITY FOR PURPOSES OF THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT OF 1996 (“HIPAA”), NOR IS THE INFORMATION PROVIDED BY YOU TO COMPANY CONSIDERED PROTECTED HEALTH INFORMATION UNDER HIPAA. AS SUCH, THE ADDITIONAL PRIVACY AND SECURITY PROTECTIONS AFFORDED TO CONSUMERS/PATIENTS UNDER HIPAA ARE NOT CONTEMPLATED BY, NOR CONTAINED WITHIN, THE AGREEMENT. </p>
      <p><strong>1. Acceptance of Agreement. </strong> You agree to the terms and conditions outlined in the Agreement with respect to your use of the Website including, but not limited to, your purchase of Online Products through this Website. This Agreement constitutes the entire and only agreement between you and Company with respect to your use of the Website and supersedes all prior or contemporaneous agreements, representations, warranties and/or understandings with respect to your use of the Website, the content contained therein and/or the analyses, research, opinions and other information provided by or through the Website. Company may change the Agreement, in whole or in part, at any time without specific notice to you. The latest Agreement will be posted on the Website. Your continued use of the Website following posted notice constitutes your acceptance of all of the terms and conditions contained within the Agreement in effect at that time. Therefore, you should regularly check this page for updates and/or changes. Unless explicitly stated otherwise, any future offer(s) or product(s) made available to you on the Website that augment(s) or otherwise enhance(s) the current features of the Website shall be subject to the Agreement posted at the time of your purchase. Company is not responsible or liable in any manner whatsoever for your inability to use the Website and/or obtain any Online Products. The Website and Products offered are available only to individuals who are at least eighteen (18) years of age and can enter into legally binding contracts. Company reserves the right, in its sole discretion, to deny any order of anyone at any time and for any reason, whatsoever. You certify that you are eighteen (18) years of age and agree to provide true, accurate, current and complete information when prompted for such information. </p>
      <p><strong>2. Orders/Billing. </strong>In consideration for the Products you order from Company, you agree to pay the sums listed below at the time such sums are due and owing. You shall have the choice to pay with a credit card or debit card. Company's authorization to provide and bill you is obtained by way of your electronic signature. Once an electronic signature is submitted, this electronic order constitutes an electronic letter of agency. Company's reliance upon your electronic signature is specifically sanctioned by the Uniform Electronic Transactions Act and the Electronic Signatures in Global and National Transactions Act. Both laws specifically preempt all state laws that recognize only paper and handwritten signatures. </p>
      <p><strong>Contact Us.</strong> If you have any questions about the Agreement, Product or about the practices of Company, please feel free to call us at <br />
    <?php print US_SITE_PH_NO; ?> Mon - Fri from 9am – 6pm MST.</p></td>
  </tr>
</table>
</body>
</html>
