
<!--<br />&copy; Copyright <?php echo date("y");?>  <?php print COMPANY_NAME; ?> - <?php print COMPANY_ADDRESS; ?> . All Rights Reserved Worldwide<br />
Toll Free <?php print SITE_PH_NO; ?><br /><br />
These statements have not been reviewed by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease.
Equinox Day &amp; Night is not affiliated in any way with CNN, FOX, WebMD, ABC, FORTUNE, NBC or CNN, FOX, WebMD, ABC, FORTUNE, NBC, New York Times, Harvard University, and Nebraska University are registered trademarks of their respective owners.<br /><br />
Product is not affiliated in any way with any of the company/companies whose trademarks, logos and/or service marks appear throughout this website. All trademarks, logos, and service marks (collectively the "Trademarks") displayed are registered and/or unregistered Trademarks of their respective owners. Images associated with the testimonials do not represent the actual person. Results not Typical.<br />
<br />The regular price of <?php print PRODUCT_NAME; ?> is <?php print TOTAL_AMOUNT; ?>. For the trial offer your credit card will be charged only $<?php print SHIP_AMT; ?> for 1 month supply of <?php print PRODUCT_NAME; ?>. You will have 14 days from your original purchase date to decide if <?php print PRODUCT_NAME_SHORT; ?> is right for you. If you are satisfied with <?php print PRODUCT_NAME_SHORT; ?>, you need to do nothing, and at the end of your 14 day trial period you will be charged only $<?php print ACTUAL_AMOUNT; ?> for a 30 day supply of <?php print PRODUCT_NAME_SHORT; ?>. Approximately 30 days from your original purchase date and every 30 days thereafter you will be sent another fresh Supply of <?php print PRODUCT_NAME_SHORT; ?> and your credit card on file will be billed <?php print TOTAL_AMOUNT; ?>. You can cancel anytime simply by contacting our Customer Care and Support staff. There is no obligation to remain in the program and you can discontinue future shipments at any time. But we do have a limit which is one <?php print PRODUCT_NAME_SHORT; ?> Trial per household.-->
<style type="text/css">
  .footer-text {font-family: arial; font-size: 9pt; font-weight: normal; margin: 0px; padding:0px; line-height:18px;}
  .footer-textb {font-family: arial; font-size: 10pt; font-weight: bold; margin: 0px; padding:0px; line-height:18px;}
  </style> 
  
  <?php echo $_SESSION['pages']->disclaimer;?>